### ISSUE TITLE
does not report values correctly when running as a container?

### ISSUE THREAD

**Issue by ohadlevy** [ori-amizur/introspector#7]
Not sure it might be a PBKAC but when running as a container (e.g. ``` podman run quay.io/oamizur/introspector introspector -text``` as a container vs running it directly on my system I'm getting different values (network, blk devices etc), how are you planning to report actual values for the host its running on vs the container?

**Comment by ori-amizur** [comment]
Concerning network, we should run it as net=host and privileged to get same results.
The privileged flag should apply to the block devices as well.
The mount points will be removed from the output as it is unimportant to what we want to achieve.
The implementation of these, and the interfaces will have to change.  It was done for the initial demo.  Now we will probably have to decide, on the fields in the output.

**Comment by ohadlevy** [comment]
thanks, ```net=host``` did get me getting more information,perhaps should be added to the readme.
```privileged``` did not made any noticeable output
